### ISSUE TITLE
Error loading indices  on  7.13.4-debian-10-r*

### ISSUE THREAD

**Issue by gtxx3600** [bitnami/bitnami-docker-kibana#51]
**Description**

Kibana shows "Error loading indices"  "Index Management" page

**Steps to reproduce the issue:**

1. Install kibana 7.13.4-debian-10-r*
2. config and connect kibana to a es cluster
3. enter the "Index Management" page

This problem is caused by a known issue of kibana, which is fixed by [this commit](https://github.com/elastic/kibana/commit/d7ccba7c6e9e3e4a875cf0b4e0910a000802f220#diff-ad1e5e4de124168f8c7de1a1adc20a1e8537dc52d96905afe13628261552e12f)

Please use a newer version of kibana code (after 2 Jul)

**Comment by pablogalegoc** [comment]
Hi @gtxx3600!

Our pipeline monitors closely the new releases of the assets in order to automatically create our own new releases. This commit that you point seems to be included in the 7.14.0 release, so once it is detected and passes the tests it will be released but I cannot give you an ETA unfortunately.
